# Generated by Django 4.2.5 on 2024-03-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0004_rename_kodepenyusun_konversimaster_idkodepenyusun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoawalbahanbaku',
            old_name='IDBahanBaku',
            new_name='KodeProduk',
        ),
    ]
