# Generated by Django 5.0.3 on 2024-04-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0022_transactionlog_konversimaster_lastedited'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubkonKirim',
            fields=[
                ('IDSubkonKirim', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Tanggal', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('PO', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSubkonKirim',
            fields=[
                ('IDDetailSubkonKirim', models.AutoField(primary_key=True, serialize=False)),
                ('Jumlah', models.IntegerField()),
                ('KeteranganACC', models.BooleanField()),
                ('Harga', models.FloatField()),
                ('KodeProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produk')),
                ('IDSubkonKirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.subkonkirim')),
            ],
        ),
    ]
